### ISSUE TITLE
Brickset Password Issue

### ISSUE THREAD

**Issue by misterbreakout** [leolelego/Brickie-iOS#105]
When having a brickset password with the + sign in it, Brickie would not log in. Unsure if it happens with other sexual characters, but removing the + sign from the password correct the issue. 

Platform: IOS 15 on iPhone XR.

**Comment by leolelego** [comment]
Thanks @misterbreakout for the reporting!
And this work fine on brickset.com ?
let me dig and find a fix!

**Comment by leolelego** [comment]
Update
I found where the issue is. but I don't know how to solve it. String to URL automatically encode to replace caracters. I'm quite stuck for now. 
I need to dig more!

**Comment by dmlebron** [comment]
hey @leolelego I create this #110 to address this issue

**Comment by leolelego** [comment]
Thanks @dmlebron I will check and test the PR really soon. This is really helpful!

**Comment by leolelego** [comment]
@dmlebron all good, allQueries for the APIKey is a great idea. thanks. I added you in the RN.
@misterbreakout you could test soon or use the [TestFlight version](https://testflight.apple.com/join/9IE197Mt) to test.
