### ISSUE TITLE
Lego set barcode scanning not working

### ISSUE THREAD

**Issue by robbyrob8** [leolelego/Brickie-iOS#68]
I just discovered this wonderful app today but for some reason the barcode scanner doesn’t seem to work. Actually, it works but doesn’t find the set in the brickset database. Not sure if it is because I am in Canada but I thought UPC barcodes were universal.

**Comment by leolelego** [comment]
Hey @robbyrob8 !
thanks, can you give me the code bar and the set number? I will check on Brickset database if the issue comes to me or Brickset. 

Sorry for the delay, I was not really available these days. ;)

**Comment by leolelego** [comment]
I have improved the scan experience in 1.3.1. Let me know if the issue occur again! 
In this case, please attach barcode for exemple.

**Comment by robbyrob8** [comment]
Hi @leolelego , thank you for getting back to me. I will download the latest version, test, and let you know if my issue went away.

**Comment by robbyrob8** [comment]
Still having the same issue. Please see screenshots where I first tried using the barcode scanner to scan the set's barcode. It scanned the barcode correctly but failed in loading the set from Brickset. However, it easily found the set when I entered the set number so the connection to Brickset seems to be fine.
<img width="425" alt="Screen Shot 2021-08-02 at 11 34 24 PM" src="https://user-images.githubusercontent.com/78328363/127953870-f0e7630a-384b-4650-878d-82bdb09d13db.png">
<img width="241" alt="Screen Shot 2021-08-02 at 11 34 14 PM" src="https://user-images.githubusercontent.com/78328363/127953872-54d38303-a556-4b3b-899a-562a6ddfa0af.png">
<img width="685" alt="Screen Shot 2021-08-02 at 11 33 57 PM" src="https://user-images.githubusercontent.com/78328363/127953875-1e6c1ade-f7df-4b59-94d3-19c9283e0c54.png">
<img width="421" alt="Screen Shot 2021-08-02 at 11 33 44 PM" src="https://user-images.githubusercontent.com/78328363/127953881-1ddc6c1e-3b83-470c-b5e8-573c9803c6c4.png">

**Comment by leolelego** [comment]
Hi @robbyrob8
Apparently the EAN code for this set on brickset is 5702016365436. They don't reference the code you have. 

https://brickset.com/sets/70421-1/El-Fuego-s-Stunt-Truck
On the right panel at the bottom. 

As the information is searched from brickset dataset I can't add it myself. 
Perhaps Canada has different EAN code than Europe (Brickset is Located in Europe). 
I saw that some sets have multiple EAN code, you can perhaps reach Brickset to add the one you have. 

But I will add a message on the app telling something like "all EAN code are not referenced, contact Brickset to add one you can't find here". 

Thanks for the notice 😊

**Comment by robbyrob8** [comment]
Thank you for investigating this so quickly @leolelego !

That's interesting that the barcodes seem to be different in other countries. I will look into this further also because perhaps we can find a nice solution. I believe that Canada has the same barcodes as the USA so it would be great if the huge population there could enjoy your app too. :)

**Comment by leolelego** [comment]
Totally agreed! North America is a big place for Lego fan, so if I can do something, I will 😊

**Comment by robbyrob8** [comment]
I was looking into this a bit and found that brickset.com does show the UPC and EAN for some sets like this one:
[https://brickset.com/sets/75208-1/Yoda-s-Hut](url)

Not sure if you'd be able to add something to your code to look for the UPC if the barcode scanned only has 12 digits, otherwise, look at the EAN if it has 13 digits?

Also, I noticed in the app that there's no way to cancel out of the barcode scanning screen if you tap it by accident and don't have a barcode to scan. Not sure if I'm missing a gesture like swipe left or something to do that.

**Comment by leolelego** [comment]
I need to check if the API add UPC code. In this case I will integrate. 

For the "no way out" I have added a cross in the next build. But meantime you can use the swipe gesture from the top to bottom. 

If you are familiar with Beta and TestFlight you can use the vets here: https://testflight.apple.com/join/9IE197Mt

**Comment by leolelego** [comment]
Thanks for you help @robbyrob8 
It will be done in 1.4, which should be shipped soon
