### ISSUE TITLE
Certain sets crash app

### ISSUE THREAD

**Issue by HPStormtrooper** [leolelego/Brickie-iOS#69]
I have quite a few sets and most I had no issues but there are 4 I have been unable to add. Every time I open it whether w/the barcode or through search it immediately crashes the app. The Star Wars Boba Fett helmet is one of them... not sure if it a bug or?

**Comment by Jay-Seeby** [comment]
Yes, I encountered this problem with 10265 Ford Mustang. When I click on the thumbnail, the detail screen pops-up briefly, then app crashes to iPadOS.

**Comment by PixelatedPsycho** [comment]
I’ve also encountered this with sets 7703 and 70827

**Comment by leolelego** [comment]
Thanks guys, 

I need to find time the check these, sorry for the inconvenience! 
I had the Mustang myself and no issue for now. Let's see!

**Comment by leolelego** [comment]
HI guys ,I found the issue, testing right now and should publish the update in the weekend, so the fix should be available mid next week, in function of apple.

**Comment by leolelego** [comment]
Solved in 1.3.1, let me know if the issue occur again. But this was an easy fix, so we should be good!
