### ISSUE TITLE
Wanted Figure List Appearing Empty

### ISSUE THREAD

**Issue by Ryansevel** [leolelego/Brickie-iOS#80]

**Comment by leolelego** [comment]
You right, fixing right now!

**Comment by Ryansevel** [comment]
Awesome! This is still one of best LEGO collection apps I’ve ever used. Thank you

**Comment by leolelego** [comment]
@Ryansevel  
Fixed, you should have the bug fixed in version 1.3.3 I publish now, so in fonction of Apple you could have it in 1-2 days. 
Thanks a lot for rising this issue that fast! 
I give you a small wink in my release note for this update ;)
