### ISSUE TITLE
Add swipe option to view images of sets

### ISSUE THREAD

**Issue by maxhartke** [leolelego/Brickie-iOS#90]
Instead of having to swipe down to close each image when viewing a set, add the ability to swipe to view the other images in the set. Maybe add arrows and status dots like the image below. Also maybe increase the area to swipe down to close an image as it doesn't feel natural right now. P.S. I really admire your app, let me know if there's anything I can help with. 
![image](https://user-images.githubusercontent.com/56495123/128588848-2c9f9287-2bf3-43ff-bd26-8106a7bed568.jpeg)

**Comment by leolelego** [comment]
Nice idea Max! 
Definitely something I can do 😊 

I will start the dev of the next version in Sept / Oct. 

But if you have any Swift/SwiftUI skills feel free to do it.
I have just a concern between swipe and zoom gesture. I need to make this feel natural. 

And thanks for your feedback, really appreciate to see that some
people like it, that give motivation 😊

**Comment by maxhartke** [comment]
Hey Lèo,

**Comment by leolelego** [comment]
Thanks @maxhartke ! Feel free to correct me, I'm not English, just pretend too ^^

**Comment by leolelego** [comment]
@maxhartke you will like this! Should be for 1.4 - You can join the beta here: 

https://user-images.githubusercontent.com/4069471/137214178-1506ad6c-4f2d-4fd8-99de-444ef56ef2aa.mp4
